### ISSUE TITLE
Slot reuse - consequences for documentation

### ISSUE THREAD

**Issue by mslw** [sfb1451/crc-schema-draft#1]
The Slots available for a class can be defined in two ways: either directly inside class definition (as "attributes"), or independently as Slots (which are added to class, or potentially several classes, as "slots"). See linkml [Tutorial](https://linkml.io/linkml/intro/tutorial07.html) and [FAQ](https://linkml.io/linkml/faq/modeling.html#when-should-i-use-attributes-vs-slots).

When a slot is used in a class, it is possible to refine its meaning with `slot_usage` (see: [slot usage](https://linkml.io/linkml/schemas/slots.html#slot-usage)), including giving it a class-specific description.

However, the documentation pages are generated for slots. The class page shows a table of slots, but their descriptions are truncated - either at first sentence (actually, first dot, so trimming also at the first "e.g." or "i.e." ), or after a certain number of characters, replacing the rest with an ellipsis. This happens in the Markdown generation step, not in the html template!

And here comes a potential inconvenience.

### Defining slots as attributes

So if we have a class that defines its slots as attributes, including a lengthy description (for a slot that is also called description - sorry about the ambiguity):

``` yaml
classes:
  Dataset:
    attributes:
      description:
        slot_uri: schema:description
        required: true
        description: >-
          General description of the dataset. It may summarize its
          purpose, scope, content, and potential applications. If a
          long description need to be split into paragraphs, each
          paragraph can be put into a dedicated column in this
          row. Language must be English.
```
 we see the truncated description in the class page:

![image](https://github.com/sfb1451/crc-schema-draft/assets/11985212/e7296791-cbe1-49ea-b753-c89eba727d41)

But the slot page (seen after clicking the slot name) lists the description in full (here truncated by just me taking a screenshot)

![image](https://github.com/sfb1451/crc-schema-draft/assets/11985212/725b769d-7ac7-458c-8336-a1baa6806e1c)

So far so good.

### Defining slots on their own

However, for a slot that is defined on its own and added to the class with `slot_usage` override (e.g. because we want to use `schema:description` on several classes, with a more precise description for each one):

``` yaml
classes:
  Dataset:
    slots:
      - description
    slot_usage:
      description:
        required: true
        description: >-
          General description of the dataset. It may summarize its
          purpose, scope, content, and potential applications. If a
          long description need to be split into paragraphs, each
          paragraph can be put into a dedicated column in this
          row. Language must be English.
slots:
  description:
    slot_uri: schema:description
    description: A description of the item.
```

... the class page would still only show the truncated description in the table (a full description can be found by expanding the "LinkML source" section, but it is hardly optimal):

![image](https://github.com/sfb1451/crc-schema-draft/assets/11985212/96789659-6751-479e-a39e-308fde11ba79)

... and link to a *generic* slot definition, which only shows "class modifies slot: yes".

![image](https://github.com/sfb1451/crc-schema-draft/assets/11985212/ebf4b76d-d705-400e-acef-a39050e6d877)

You can see and play with the second example in the [slot-reuse](https://github.com/sfb1451/crc-schema-draft/tree/slot-reuse) branch of this repo.

At this moment I am not sure whether this behavior is modifiable (I would appreciate the ability to show non-truncated description in the class page), and whether it is a problem for our imagined use case - time will tell.
